---
- name: Audit Kepatuhan RHEL 9 dengan OpenSCAP
  hosts: rhel9_servers
  become: yes
  gather_facts: no

  tasks:
    - name: Pastikan tool OpenSCAP dan panduan keamanan RHEL 9 terinstal
      ansible.builtin.package:
        name:
          - openscap-scanner
          - scap-security-guide
        state: present

    - name: Jalankan pemindaian OpenSCAP terhadap profil CIS RHEL 9
      ansible.builtin.command: >
        oscap xccdf eval
        --profile cis_redhat_enterprise_linux_9_profile
        --report /tmp/report-rhel9-{{ inventory_hostname }}.html
        /usr/share/xml/scap/ssg/content/ssg-rhel9-ds.xml
      register: scan_result
      changed_when: "'fail' in scan_result.stdout"
